version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: grad-postgres
    environment:
      POSTGRES_DB: gradproject
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: grad-backend
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: init-configs
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gradproject
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8081:8081"
    command: ["java", "-jar", "/app.jar"]
    volumes:
      - ~/.m2:/root/.m2

volumes:
  postgres_data:
