package jordan.university.gradproject2.enums;

public enum Status {
    NEW,
    MODIFICATION,
    APPROVED,
    REJECTED,
    RECEIVED,
    PENDING_SUPERVISOR_REVIEW,
    SUPERVISOR_APPROVED,
    SUPERVISOR_REJECTED,
    PENDING_FACULTY_REVIEW,
    FACULTY_REVIEWED,
    FACULTY_APPROVED,
    FACULTY_REJECTED,
    PENDING_UNION_REVIEW,
    UNION_REVIEWED,
    INVESTMENT_CENTER_REVIEW,
    INVESTMENT_CENTER_APPROVED,
    INVESTMENT_CENTER_REJECTED,
    PENDING_DEANSHIP_REVIEW,
    DEANSHIP_APPROVED,
    DEANSHIP_REJECTED
}
